// YuChe Liu
#pragma config(StandardModel, "RVW SQUAREBOT")
#pragma config(RenamedStdModelSensor, in1, linetracker1)
#pragma config(RenamedStdModelSensor, in2, linetracker2)
#pragma config(RenamedStdModelSensor, in3, linetracker3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// custom functions 
void turnLeft(){
    motor[leftmotor]=-30;
    motor[rightmotor]=30;
	wait1Msec(1550);
}
void turnRight(){
    motor[leftmotor]=30;
	motor[rightmotor]=-30;
	wait1Msec(1050);
}


task main()
{
	int speed = 63;
	// move forward to stand outside the startbox
	motor[rightMotor] = 127;
	motor[leftMotor]  = 127;
	wait1Msec(2050);

	// find the line
	bool flag = true;
	while(flag){
		motor[leftmotor]=50;
		motor[rightmotor]=50;
		// if we find the black line, we turn left
		if(SensorValue(linetracker2) > 1400){
			turnLeft();
			flag=false;
		}
	}
	
bool flag2=true;
while(flag2){
		// if we are too close to the wall, the vehicle stops in front of it.
		if(speed<20){
			flag2=false;
		}
		// if left line tracker cannot sense the blackline, we turn right
		if(SensorValue(linetracker1) < 1200){
		motor[leftmotor]=60;
		motor[rightmotor]=0;
		}
		// if right line tracker cannot sense the blackline, we turn left
		if(SensorValue(linetracker3) < 1200){
		motor[leftmotor]=0;
		motor[rightmotor]=60;
		}
		// if we are above the blackline, we keep moving forward
		if(SensorValue(linetracker1) > 1000 && SensorValue(linetracker3) > 1000){
		motor[leftmotor]=speed;
		motor[rightmotor]=speed;
		}
		// if we are in a corner where we sense right SensorValue is huge and left SensorValue is tiny
		// we need to turn right dramtically by using my own function declared top
		if(SensorValue(linetracker3) > 1400 && SensorValue(linetracker1) < 300 ){
			turnRight();
		}
		// if we are close to wall, we slow down a bit
		if(SensorValue(sonarSensor) < 32 && SensorValue(sonarSensor) > 25){
				speed = speed-2;
		};
	
	
	}


}